- name: Demonstrates use of docker_container module
  hosts: localhost
  tasks:
    - name: Provision Ubuntu docker container
      docker_container:
          image: "tektutor/ansible-ubuntu"
          name: "ubuntu{{item}}"
          hostname: "ubuntu{{item}}"
          state: started
          ports:
            - "800{{item}}:80"
            - "200{{item}}:22"
      with_sequence: start=1 end=4

    - name: Provision CentOS docker container
      docker_container:
          image: "tektutor/ansible-centos"
          name: "centos{{item}}"
          hostname: "centos{{item}}"
          state: started
          ports:
            - "800{{item}}:80"
            - "200{{item}}:22"
      with_sequence: start=5 end=8
